# Generated by Django 5.2.9 on 2025-12-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài học')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/')),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('mixed', 'Mixed Skills'), ('review', 'Review'), ('test', 'Test')], db_index=True, default='mixed', max_length=20, verbose_name='Loại bài học')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Độ khó (1-10)')),
                ('content_html', models.TextField(blank=True, verbose_name='Nội dung HTML')),
                ('objectives', models.JSONField(blank=True, default=list, verbose_name='Mục tiêu học tập')),
                ('estimated_minutes', models.PositiveIntegerField(default=15, verbose_name='Thời gian ước tính (phút)')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='XP thưởng')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Nội dung Premium')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'db_table': 'lessons',
                'ordering': ['unit', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên khóa học')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Hình thu nhỏ')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency')], db_index=True, default='A1', max_length=2, verbose_name='Trình độ CEFR')),
                ('estimated_hours', models.PositiveIntegerField(default=0, verbose_name='Thời gian ước tính (giờ)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('is_free', models.BooleanField(default=False, verbose_name='Miễn phí')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'db_table': 'courses',
                'ordering': ['cefr_level', 'order', 'title'],
                'indexes': [models.Index(fields=['status', 'cefr_level'], name='courses_status_36a75d_idx'), models.Index(fields=['is_featured', 'status'], name='courses_is_feat_b15816_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Nội dung câu')),
                ('text_vi', models.TextField(blank=True, verbose_name='Bản dịch tiếng Việt')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sentences/audio/', verbose_name='File âm thanh')),
                ('audio_duration', models.FloatField(default=0, verbose_name='Thời lượng (giây)')),
                ('ipa_transcription', models.CharField(blank=True, max_length=500, verbose_name='Phiên âm IPA')),
                ('grammar_analysis', models.JSONField(blank=True, default=dict, verbose_name='Phân tích ngữ pháp')),
                ('vocabulary_highlights', models.JSONField(blank=True, default=list, verbose_name='Từ vựng nổi bật')),
                ('sentence_type', models.CharField(choices=[('statement', 'Statement'), ('question', 'Question'), ('exclamation', 'Exclamation'), ('imperative', 'Imperative'), ('dialogue', 'Dialogue')], default='statement', max_length=20)),
                ('audio_slow', models.FileField(blank=True, null=True, upload_to='sentences/audio_slow/', verbose_name='Audio chậm')),
                ('context', models.CharField(blank=True, max_length=500, verbose_name='Ngữ cảnh')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='curriculum.lesson', verbose_name='Bài học')),
            ],
            options={
                'verbose_name': 'Câu',
                'verbose_name_plural': 'Câu',
                'db_table': 'sentences',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField(verbose_name='Mặt trước (từ/câu hỏi)')),
                ('back_text', models.TextField(verbose_name='Mặt sau (định nghĩa/đáp án)')),
                ('front_audio', models.FileField(blank=True, null=True, upload_to='flashcards/audio/', verbose_name='Audio mặt trước')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/', verbose_name='Hình mặt trước')),
                ('ipa', models.CharField(blank=True, max_length=200, verbose_name='Phiên âm IPA')),
                ('examples', models.JSONField(blank=True, default=list, verbose_name='Câu ví dụ')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='Từ loại')),
                ('card_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('phrase', 'Phrase'), ('sentence', 'Sentence'), ('grammar', 'Grammar Point'), ('idiom', 'Idiom'), ('collocation', 'Collocation')], db_index=True, default='vocabulary', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Độ khó (1-5)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='curriculum.lesson', verbose_name='Bài học')),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='curriculum.sentence', verbose_name='Câu liên quan')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'db_table': 'flashcards',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên unit')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='units/thumbnails/')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Chủ đề')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.unit', verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên quy tắc')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Danh mục')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency')], db_index=True, default='A1', max_length=2)),
                ('explanation_html', models.TextField(verbose_name='Giải thích')),
                ('explanation_vi', models.TextField(blank=True, verbose_name='Giải thích tiếng Việt')),
                ('structure', models.CharField(blank=True, max_length=500, verbose_name='Cấu trúc')),
                ('examples', models.JSONField(blank=True, default=list, verbose_name='Ví dụ')),
                ('common_mistakes', models.JSONField(blank=True, default=list, verbose_name='Lỗi thường gặp')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_rules', models.ManyToManyField(blank=True, to='curriculum.grammarrule', verbose_name='Quy tắc liên quan')),
            ],
            options={
                'verbose_name': 'Quy tắc ngữ pháp',
                'verbose_name_plural': 'Quy tắc ngữ pháp',
                'db_table': 'grammar_rules',
                'ordering': ['category', 'order', 'title'],
                'indexes': [models.Index(fields=['category', 'cefr_level'], name='grammar_rul_categor_b72898_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['lesson', 'order'], name='sentences_lesson__5f2068_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['lesson', 'card_type'], name='flashcards_lesson__3445c3_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['card_type', 'is_active'], name='flashcards_card_ty_fcfc50_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['course', 'status', 'order'], name='units_course__14453a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit', 'status', 'order'], name='lessons_unit_id_6c83fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type', 'status'], name='lessons_lesson__21226c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'slug')},
        ),
    ]
