# Generated by Django 5.2.9 on 2025-12-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_phonemecategory_phoneme_minimalpair_phonemeword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('native', 'Native Speaker Recording'), ('tts', 'TTS Generated (Cached)'), ('generated', 'TTS Generated (On-Demand)')], db_index=True, max_length=20, verbose_name='Loại nguồn âm thanh')),
                ('voice_id', models.CharField(blank=True, db_index=True, default='en-US-AriaNeural', max_length=50, verbose_name='ID giọng nói TTS')),
                ('language', models.CharField(default='en-US', max_length=10, verbose_name='Ngôn ngữ')),
                ('audio_file', models.FileField(upload_to='phonemes/audio/%Y/%m/%d/', verbose_name='File âm thanh')),
                ('audio_duration', models.FloatField(default=0, verbose_name='Thời lượng (giây)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata bổ sung')),
                ('cached_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Lưu cache đến')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sources', to='curriculum.phoneme', verbose_name='Âm vị')),
            ],
            options={
                'verbose_name': 'Audio Source',
                'verbose_name_plural': 'Audio Sources',
                'db_table': 'curriculum_audiosource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước file (bytes)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo cache')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Lần truy cập cuối')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Số lần phát')),
                ('audio_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='curriculum.audiosource', verbose_name='Audio Source')),
            ],
            options={
                'verbose_name': 'Audio Cache',
                'verbose_name_plural': 'Audio Caches',
                'db_table': 'curriculum_audiocache',
            },
        ),
        migrations.AddField(
            model_name='phonemecategory',
            name='preferred_audio_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_phoneme', to='curriculum.audiosource', verbose_name='Audio ưu tiên'),
        ),
        migrations.AddIndex(
            model_name='audiosource',
            index=models.Index(fields=['phoneme', 'source_type'], name='curriculum__phoneme_e33067_idx'),
        ),
        migrations.AddIndex(
            model_name='audiosource',
            index=models.Index(fields=['voice_id', 'created_at'], name='curriculum__voice_i_4c5018_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocache',
            index=models.Index(fields=['usage_count', '-last_accessed_at'], name='curriculum__usage_c_6e848b_idx'),
        ),
    ]
