# Generated by Django 5.2.9 on 2025-12-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_add_audiosource_audiocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneme',
            name='preferred_audio_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_phoneme', to='curriculum.audiosource', verbose_name='Audio ưu tiên'),
        ),
        migrations.AlterField(
            model_name='phonemecategory',
            name='preferred_audio_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_phonemes', to='curriculum.audiosource', verbose_name='Audio ưu tiên'),
        ),
    ]
