# Generated by Django 5.2.9 on 2025-12-17 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_phoneme_preferred_audio_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Auto-increment cho mỗi phoneme', verbose_name='Số phiên bản')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Chỉ có 1 version active cho mỗi phoneme', verbose_name='Đang sử dụng')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm version này được activate', verbose_name='Có hiệu lực từ')),
                ('effective_until', models.DateTimeField(blank=True, help_text='Thời điểm version này bị deactivate (None = vẫn active)', null=True, verbose_name='Hết hiệu lực')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('change_reason', models.TextField(blank=True, help_text='Ví dụ: "Giọng rõ hơn", "Fix background noise"', verbose_name='Lý do thay đổi')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Đếm số lần audio được phát', verbose_name='Số lần phát')),
                ('avg_user_rating', models.FloatField(blank=True, help_text='Rating trung bình từ users (1-5 sao)', null=True, verbose_name='Đánh giá TB')),
                ('user_rating_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt đánh giá')),
                ('audio_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='curriculum.audiosource', verbose_name='Audio Source')),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_versions', to='curriculum.phoneme', verbose_name='Âm vị')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio_versions', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Audio Version',
                'verbose_name_plural': 'Audio Versions',
                'db_table': 'curriculum_audio_version',
                'ordering': ['phoneme', '-version_number'],
                'indexes': [models.Index(fields=['phoneme', 'is_active'], name='curriculum__phoneme_4ae0ab_idx'), models.Index(fields=['effective_from'], name='curriculum__effecti_b02444_idx'), models.Index(fields=['-version_number'], name='curriculum__version_14554b_idx')],
                'unique_together': {('phoneme', 'version_number')},
            },
        ),
    ]
