# Generated by Django 5.2.9 on 2026-01-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_add_audio_versioning"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pronunciationlesson",
            options={
                "ordering": ["stage__order", "part_number", "unit_number", "order"],
                "verbose_name": "Bài học phát âm",
                "verbose_name_plural": "Bài học phát âm",
            },
        ),
        migrations.AddField(
            model_name="phoneme",
            name="vietnamese_comparison",
            field=models.TextField(
                blank=True,
                help_text="Ví dụ: /p/ tiếng Anh bật hơi mạnh hơn /p/ tiếng Việt",
                verbose_name="So sánh với tiếng Việt",
            ),
        ),
        migrations.AddField(
            model_name="phoneme",
            name="vietnamese_mistake_audio",
            field=models.FileField(
                blank=True,
                help_text="Recording demonstrating the common mistake",
                null=True,
                upload_to="phonemes/mistake_audio/",
                verbose_name="Audio lỗi người Việt hay mắc",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="1-4", unique=True, verbose_name="Số giai đoạn"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên giai đoạn"),
                ),
                (
                    "name_vi",
                    models.CharField(max_length=100, verbose_name="Tên tiếng Việt"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "description_vi",
                    models.TextField(blank=True, verbose_name="Mô tả tiếng Việt"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class",
                        max_length=50,
                        verbose_name="Icon class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#F47C26", max_length=20, verbose_name="Màu đại diện"
                    ),
                ),
                (
                    "focus_area",
                    models.TextField(
                        blank=True,
                        help_text="Ví dụ: Khẩu hình miệng, Rung cổ họng, etc.",
                        verbose_name="Trọng tâm",
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of learning objectives",
                        verbose_name="Mục tiêu học tập",
                    ),
                ),
                (
                    "estimated_lessons",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Số bài học ước tính"
                    ),
                ),
                (
                    "estimated_hours",
                    models.FloatField(
                        default=0, verbose_name="Thời gian ước tính (giờ)"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_previous_stages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unlocks_stages",
                        to="curriculum.curriculumstage",
                        verbose_name="Giai đoạn tiên quyết",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giai đoạn học",
                "verbose_name_plural": "Giai đoạn học",
                "db_table": "curriculum_stages",
                "ordering": ["order", "number"],
            },
        ),
        migrations.AddField(
            model_name="pronunciationlesson",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Giai đoạn học (1-4)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="curriculum.curriculumstage",
                verbose_name="Giai đoạn",
            ),
        ),
    ]
