# Generated by Django 5.2.9 on 2026-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_pronunciationlesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='easy', max_length=10, verbose_name='Mức độ khó'),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
    ]
