# Generated by Django 5.2.9 on 2026-01-05 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_tonguetwister_difficulty_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonemeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(help_text='0-100', verbose_name='Accuracy (%)')),
                ('attempt_duration', models.FloatField(default=0, verbose_name='Duration (seconds)')),
                ('exercise_type', models.CharField(blank=True, help_text='tongue_twister, minimal_pair, production, etc.', max_length=50, verbose_name='Exercise Type')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='user_phoneme_attempts/%Y/%m/%d/', verbose_name='Audio Recording')),
                ('transcript_text', models.TextField(blank=True, help_text='STT output', verbose_name='Transcript')),
                ('target_text', models.TextField(blank=True, help_text='Expected text (for tongue twisters)', verbose_name='Target Text')),
                ('phoneme_analysis', models.JSONField(blank=True, default=dict, help_text='Detailed phoneme-level results from Phase 5.2', verbose_name='Phoneme Analysis')),
                ('problem_phonemes', models.JSONField(blank=True, default=list, help_text='List of problematic phonemes in this attempt', verbose_name='Problem Phonemes')),
                ('pronunciation_score', models.FloatField(default=0, verbose_name='Pronunciation Score')),
                ('fluency_score', models.FloatField(default=0, verbose_name='Fluency Score')),
                ('completeness_score', models.FloatField(default=0, verbose_name='Completeness Score')),
                ('ai_feedback', models.TextField(blank=True, help_text='Auto-generated feedback', verbose_name='AI Feedback')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Attempted At')),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.phoneme', verbose_name='Phoneme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Phoneme Attempt',
                'verbose_name_plural': 'Phoneme Attempts',
                'db_table': 'phoneme_attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', '-attempted_at'], name='phoneme_att_user_id_f88fb8_idx'), models.Index(fields=['phoneme', '-attempted_at'], name='phoneme_att_phoneme_74fd09_idx'), models.Index(fields=['exercise_type', '-attempted_at'], name='phoneme_att_exercis_f4a76f_idx')],
            },
        ),
    ]
