# Generated by Django 5.2.9 on 2025-12-08 07:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('code', models.SlugField(unique=True, verbose_name='Mã')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(default='trophy', max_length=50, verbose_name='Icon')),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Hình huy hiệu')),
                ('category', models.CharField(choices=[('streak', 'Chuỗi ngày học'), ('xp', 'Điểm kinh nghiệm'), ('lessons', 'Bài học'), ('flashcards', 'Flashcards'), ('accuracy', 'Độ chính xác'), ('special', 'Đặc biệt')], default='special', max_length=20, verbose_name='Danh mục')),
                ('requirement_type', models.CharField(max_length=50, verbose_name='Loại yêu cầu')),
                ('requirement_value', models.PositiveIntegerField(verbose_name='Giá trị yêu cầu')),
                ('requirement_config', models.JSONField(blank=True, default=dict, verbose_name='Cấu hình yêu cầu')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='XP thưởng')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Ẩn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thành tựu',
                'verbose_name_plural': 'Thành tựu',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('current_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], default='A1', max_length=2, verbose_name='Trình độ hiện tại')),
                ('target_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], default='B2', max_length=2, verbose_name='Mục tiêu')),
                ('native_language', models.CharField(default='Vietnamese', max_length=50, verbose_name='Ngôn ngữ mẹ đẻ')),
                ('xp_points', models.PositiveIntegerField(default=0, verbose_name='Điểm kinh nghiệm')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Chuỗi ngày học')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Chuỗi dài nhất')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='Ngày học gần nhất')),
                ('daily_goal_minutes', models.PositiveIntegerField(default=15, verbose_name='Mục tiêu hàng ngày (phút)')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Tài khoản Premium')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Premium hết hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Miễn phí'), ('basic', 'Cơ bản'), ('premium', 'Premium'), ('vip', 'VIP')], default='free', max_length=10, verbose_name='Gói')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Đã hết hạn'), ('cancelled', 'Đã hủy'), ('paused', 'Tạm dừng')], default='active', max_length=10, verbose_name='Trạng thái')),
                ('starts_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='Tự động gia hạn')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Gói đăng ký',
                'verbose_name_plural': 'Gói đăng ký',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Tiến độ (%)')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Giá trị hiện tại')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Đã mở khóa')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày mở khóa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='users.achievement', verbose_name='Thành tựu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thành tựu người dùng',
                'verbose_name_plural': 'Thành tựu người dùng',
                'ordering': ['-unlocked_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Giới thiệu')),
                ('learning_goals', models.JSONField(blank=True, default=list, help_text='VD: ["business", "travel", "ielts"]', verbose_name='Mục tiêu học tập')),
                ('interests', models.JSONField(blank=True, default=list, help_text='VD: ["movies", "music", "technology"]', verbose_name='Sở thích')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nghề nghiệp')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Quốc gia')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thành phố')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Liên kết mạng xã hội')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành onboarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Thông báo email')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Thông báo đẩy')),
                ('study_reminders', models.BooleanField(default=True, verbose_name='Nhắc nhở học tập')),
                ('reminder_time', models.TimeField(default='20:00', verbose_name='Giờ nhắc nhở')),
                ('weekly_report', models.BooleanField(default=True, verbose_name='Báo cáo hàng tuần')),
                ('sound_effects', models.BooleanField(default=True, verbose_name='Hiệu ứng âm thanh')),
                ('auto_play_audio', models.BooleanField(default=True, verbose_name='Tự động phát audio')),
                ('show_ipa', models.BooleanField(default=True, verbose_name='Hiển thị phiên âm IPA')),
                ('show_example', models.BooleanField(default=True, verbose_name='Hiển thị ví dụ')),
                ('cards_per_session', models.PositiveIntegerField(default=20, verbose_name='Số thẻ mỗi phiên')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Chế độ tối')),
                ('language', models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ giao diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cài đặt người dùng',
                'verbose_name_plural': 'Cài đặt người dùng',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_level'], name='users_user_current_c4f3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-xp_points'], name='users_user_xp_poin_5c5c91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
