# Generated by Django 5.2.9 on 2025-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Mã xác thực')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Số lần thử')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn')),
            ],
            options={
                'verbose_name': 'Xác thực email',
                'verbose_name_plural': 'Xác thực email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='users_email_email_a0f341_idx')],
            },
        ),
    ]
