# Generated by Django 5.2.9 on 2025-12-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác thực'),
        ),
    ]
