# Generated by Django 5.2.9 on 2025-12-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_phonemecategory_phoneme_minimalpair_phonemeword_and_more'),
        ('users', '0003_emailverification_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPronunciationStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Chuỗi hiện tại')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Chuỗi dài nhất')),
                ('last_practice_date', models.DateField(blank=True, null=True, verbose_name='Ngày luyện gần nhất')),
                ('this_week_minutes', models.PositiveIntegerField(default=0, verbose_name='Phút tuần này')),
                ('this_week_lessons', models.PositiveIntegerField(default=0, verbose_name='Bài học tuần này')),
                ('total_lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Tổng bài học')),
                ('total_practice_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Tổng thời gian (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_streak', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Chuỗi luyện phát âm',
                'verbose_name_plural': 'Chuỗi luyện phát âm',
                'db_table': 'user_pronunciation_streak',
            },
        ),
        migrations.CreateModel(
            name='UserPhonemeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.PositiveSmallIntegerField(choices=[(0, 'Chưa học'), (1, 'Mới bắt đầu'), (2, 'Đang luyện tập'), (3, 'Khá tốt'), (4, 'Thành thạo'), (5, 'Hoàn hảo')], default=0, verbose_name='Mức thành thạo')),
                ('times_practiced', models.PositiveIntegerField(default=0, verbose_name='Số lần luyện tập')),
                ('times_correct', models.PositiveIntegerField(default=0, verbose_name='Số lần đúng')),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='Tỉ lệ chính xác (%)')),
                ('last_practice_accuracy', models.FloatField(default=0.0, verbose_name='Độ chính xác lần gần nhất')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='Luyện tập gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.phoneme', verbose_name='Âm vị')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_progress', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tiến độ âm vị',
                'verbose_name_plural': 'Tiến độ âm vị',
                'db_table': 'user_phoneme_progress',
                'ordering': ['-mastery_level', '-accuracy_rate'],
                'unique_together': {('user', 'phoneme')},
            },
        ),
        migrations.CreateModel(
            name='UserPronunciationLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành')], db_index=True, default='not_started', max_length=20)),
                ('current_screen', models.PositiveSmallIntegerField(default=1, verbose_name='Màn hình hiện tại')),
                ('completed_screens', models.JSONField(default=list, verbose_name='Màn hình đã hoàn thành')),
                ('screen_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu từng màn hình')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Điểm tổng')),
                ('pronunciation_accuracy', models.FloatField(default=0.0, verbose_name='Độ chính xác phát âm (%)')),
                ('listening_accuracy', models.FloatField(default=0.0, verbose_name='Độ chính xác nghe (%)')),
                ('challenge_correct', models.PositiveSmallIntegerField(default=0, verbose_name='Số câu đúng')),
                ('challenge_total', models.PositiveSmallIntegerField(default=0, verbose_name='Tổng số câu hỏi')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP nhận được')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Thời gian học (giây)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Truy cập gần nhất')),
                ('attempts', models.PositiveSmallIntegerField(default=1, verbose_name='Số lần học')),
                ('pronunciation_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.pronunciationlesson', verbose_name='Bài học phát âm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_progress', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tiến độ bài học phát âm',
                'verbose_name_plural': 'Tiến độ bài học phát âm',
                'db_table': 'user_pronunciation_lesson_progress',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('user', 'pronunciation_lesson')},
            },
        ),
    ]
