# Generated by Django 5.2.9 on 2025-12-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonemeprogress',
            name='current_stage',
            field=models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('discovered', 'Đã khám phá'), ('learning', 'Đang học lý thuyết'), ('discriminating', 'Đang luyện phân biệt'), ('producing', 'Đang luyện phát âm'), ('mastered', 'Đã thành thạo')], db_index=True, default='not_started', max_length=20, verbose_name='Giai đoạn hiện tại'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='discovery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày khám phá'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='discrimination_accuracy',
            field=models.FloatField(default=0.0, verbose_name='Độ chính xác phân biệt (0-1)'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='discrimination_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần thử phân biệt'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='discrimination_correct',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần phân biệt đúng'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='discrimination_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu luyện phân biệt'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='learning_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu học lý thuyết'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='production_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần thử phát âm'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='production_best_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm phát âm cao nhất (0-1)'),
        ),
        migrations.AddField(
            model_name='userphonemeprogress',
            name='production_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu luyện phát âm'),
        ),
    ]
