# Generated by Django 5.2.9 on 2026-01-05 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_tonguetwister_difficulty_level_and_more'),
        ('users', '0006_userphonemeprogress_current_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TongueTwisterAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='tongue_twister_recordings/%Y/%m/', verbose_name='File ghi âm')),
                ('duration', models.FloatField(help_text='Time taken to complete the tongue twister', verbose_name='Thời gian (giây)')),
                ('score', models.FloatField(default=0.0, help_text='Overall performance score', verbose_name='Điểm (0-100)')),
                ('words_detected', models.PositiveIntegerField(default=0, verbose_name='Số từ phát hiện được')),
                ('words_expected', models.PositiveIntegerField(default=0, verbose_name='Số từ dự kiến')),
                ('accuracy', models.FloatField(default=0.0, help_text='Percentage of correctly pronounced words', verbose_name='Độ chính xác (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tongue_twister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.tonguetwister', verbose_name='Câu xoắn lưỡi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tongue_twister_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lượt thử xoắn lưỡi',
                'verbose_name_plural': 'Lượt thử xoắn lưỡi',
                'db_table': 'tongue_twister_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='tongue_twis_user_id_0f3761_idx'), models.Index(fields=['tongue_twister', '-score'], name='tongue_twis_tongue__abf984_idx')],
            },
        ),
    ]
