# Generated by Django 5.2.9 on 2025-12-18 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0005_add_audio_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('oxford', 'Oxford Words'), ('pronunciation', 'Pronunciation'), ('grammar', 'Grammar'), ('idioms', 'Idioms & Phrases'), ('custom', 'Custom')], default='oxford', max_length=50)),
                ('level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('mixed', 'Mixed Levels')], max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Public decks are visible to all users')),
                ('is_official', models.BooleanField(default=False, help_text='Official decks created by admin')),
                ('icon', models.CharField(default='📚', help_text='Emoji icon', max_length=100)),
                ('color', models.CharField(default='#F47C26', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Deck',
                'verbose_name_plural': 'Flashcard Decks',
                'ordering': ['-is_official', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cards_studied', models.IntegerField(default=0)),
                ('cards_correct', models.IntegerField(default=0)),
                ('cards_incorrect', models.IntegerField(default=0)),
                ('cards_skipped', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0, help_text='Percentage of correct cards')),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('average_time_per_card', models.FloatField(default=0, help_text='Seconds per card')),
                ('notes', models.TextField(blank=True, help_text='User notes about this session')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocabulary.flashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pos', models.CharField(help_text='Part of speech: noun, verb, adj, etc.', max_length=50)),
                ('cefr_level', models.CharField(db_index=True, help_text='A1, A2, B1, B2, C1, C2', max_length=10)),
                ('ipa', models.CharField(blank=True, help_text='General IPA', max_length=100)),
                ('british_ipa', models.CharField(blank=True, help_text='UK pronunciation', max_length=100)),
                ('american_ipa', models.CharField(blank=True, help_text='US pronunciation', max_length=100)),
                ('meaning_vi', models.CharField(help_text='Vietnamese translation', max_length=500)),
                ('meaning_en', models.TextField(blank=True, help_text='English definition')),
                ('example_en', models.TextField(blank=True, help_text='English example sentence')),
                ('example_vi', models.TextField(blank=True, help_text='Vietnamese translation of example')),
                ('collocations', models.CharField(blank=True, help_text='Common word combinations: make a decision, take a photo', max_length=500)),
                ('mnemonic', models.TextField(blank=True, help_text='Memory aid or visual association for Vietnamese learners')),
                ('etymology', models.TextField(blank=True, help_text='Word origin and history')),
                ('synonyms', models.CharField(blank=True, help_text='Similar words', max_length=500)),
                ('antonyms', models.CharField(blank=True, help_text='Opposite words', max_length=500)),
                ('frequency_rank', models.IntegerField(blank=True, help_text='1 = most common, higher = less common', null=True)),
                ('register', models.CharField(blank=True, help_text='formal, informal, slang, academic', max_length=50)),
                ('audio_uk', models.FileField(blank=True, upload_to='audio/words/uk/')),
                ('audio_us', models.FileField(blank=True, upload_to='audio/words/us/')),
                ('image', models.ImageField(blank=True, upload_to='images/words/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phonemes', models.ManyToManyField(blank=True, help_text='Phonemes contained in this word', related_name='words', to='curriculum.phoneme')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['frequency_rank', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(help_text='What user sees first (usually English word or question)', max_length=500)),
                ('front_type', models.CharField(choices=[('word', 'Word'), ('sentence', 'Sentence'), ('pronunciation', 'Pronunciation'), ('grammar', 'Grammar Rule'), ('image', 'Image')], default='word', max_length=50)),
                ('back_text', models.TextField(help_text='Answer or translation')),
                ('back_example', models.TextField(blank=True, help_text='Example usage')),
                ('back_note', models.TextField(blank=True, help_text='Grammar notes or tips')),
                ('hint', models.CharField(blank=True, help_text='Hint to show before flipping card', max_length=500)),
                ('difficulty', models.IntegerField(default=3, help_text='1=very easy, 5=very hard')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: verbs, past-tense, irregular', max_length=500)),
                ('audio_url', models.URLField(blank=True, help_text='URL to pronunciation audio')),
                ('image_url', models.URLField(blank=True, help_text='URL to visual aid')),
                ('order', models.IntegerField(default=0, help_text='Display order in deck')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='vocabulary.flashcarddeck')),
                ('word', models.ForeignKey(blank=True, help_text='Link to Word model if this is a vocabulary flashcard', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness_factor', models.FloatField(default=2.5, help_text='E-Factor ranges from 1.3 to 2.5')),
                ('interval', models.IntegerField(default=1, help_text='Days until next review')),
                ('repetitions', models.IntegerField(default=0, help_text='Number of consecutive correct repetitions')),
                ('next_review_date', models.DateTimeField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_quality', models.IntegerField(blank=True, help_text='0=blackout, 3=correct with effort, 5=perfect', null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_incorrect', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0, help_text='Current correct streak')),
                ('best_streak', models.IntegerField(default=0, help_text='Best streak ever')),
                ('is_mastered', models.BooleanField(default=False, help_text='Card is mastered (interval > 30 days)')),
                ('is_learning', models.BooleanField(default=True, help_text='Card is being learned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_user_progress', to='vocabulary.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Flashcard Progress',
                'verbose_name_plural': 'User Flashcard Progress',
                'indexes': [models.Index(fields=['user', 'next_review_date'], name='vocabulary__user_id_1fd348_idx'), models.Index(fields=['user', 'is_learning'], name='vocabulary__user_id_ee3404_idx')],
                'unique_together': {('user', 'flashcard')},
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['cefr_level', 'text'], name='vocabulary__cefr_le_86d363_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['frequency_rank'], name='vocabulary__frequen_70a57f_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['pos'], name='vocabulary__pos_fea1f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('word', 'deck')},
        ),
    ]
