# Generated by Django 5.2.9 on 2025-12-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('text', 'pos', 'cefr_level')},
        ),
    ]
