# Generated by Django 5.2.9 on 2026-01-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_text_alter_word_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='cards_goal_today',
            field=models.IntegerField(default=0, help_text='Total cards learned today (including this session)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='daily_goal',
            field=models.IntegerField(default=20, help_text="User's daily goal at time of session"),
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_goal_reached',
            field=models.BooleanField(default=False, help_text='Whether daily goal was reached in this session'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='streak_count',
            field=models.IntegerField(default=0, help_text="User's streak at time of this session"),
        ),
    ]
