# Generated by Django 5.2.9 on 2026-01-07 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_studysession_cards_goal_today_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key: first_10_cards, streak_7_days, etc.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name: 🎓 First Steps', max_length=200)),
                ('description', models.TextField(help_text='Description: Learned your first 10 cards')),
                ('icon', models.CharField(help_text='Emoji or icon class: 🎓 or fas fa-trophy', max_length=50)),
                ('category', models.CharField(choices=[('milestone', 'Milestone'), ('streak', 'Streak'), ('speed', 'Speed'), ('mastery', 'Mastery'), ('level', 'Level')], max_length=50)),
                ('requirement_type', models.CharField(help_text='Type: cards_learned, streak_days, accuracy_rate, level_completed', max_length=50)),
                ('requirement_value', models.IntegerField(help_text='Required value to unlock')),
                ('requirement_data', models.JSONField(blank=True, help_text="Additional criteria: {'level': 'A1', 'timeframe': 'day'}", null=True)),
                ('points', models.IntegerField(default=10, help_text='Points awarded')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['category', 'order', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, help_text='Has user been notified about this achievement?')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_users', to='vocabulary.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
