# Generated by Django 5.2.9 on 2026-01-08 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0004_achievement_userachievement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckStudyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sessions",
                    models.IntegerField(
                        default=0, help_text="Total number of study sessions completed"
                    ),
                ),
                (
                    "total_cards_studied",
                    models.IntegerField(
                        default=0, help_text="Total cards studied across all sessions"
                    ),
                ),
                (
                    "total_time_minutes",
                    models.IntegerField(
                        default=0, help_text="Total study time in minutes"
                    ),
                ),
                (
                    "cards_new",
                    models.IntegerField(
                        default=0, help_text="Number of cards not yet studied"
                    ),
                ),
                (
                    "cards_learning",
                    models.IntegerField(
                        default=0, help_text="Number of cards currently being learned"
                    ),
                ),
                (
                    "cards_mastered",
                    models.IntegerField(
                        default=0, help_text="Number of cards mastered (SM-2 mastered)"
                    ),
                ),
                (
                    "cards_difficult",
                    models.IntegerField(
                        default=0,
                        help_text="Number of cards marked as difficult (low easiness_factor)",
                    ),
                ),
                (
                    "progress_percentage",
                    models.FloatField(
                        default=0.0, help_text="Overall progress percentage (0-100)"
                    ),
                ),
                (
                    "first_studied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When user first started studying this deck",
                    ),
                ),
                (
                    "last_studied_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When user last studied this deck"
                    ),
                ),
                (
                    "last_progress_update",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When progress stats were last calculated",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_histories",
                        to="vocabulary.flashcarddeck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deck Study History",
                "verbose_name_plural": "Deck Study Histories",
                "ordering": ["-last_studied_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_studied_at"],
                        name="vocabulary__user_id_344d10_idx",
                    ),
                    models.Index(
                        fields=["user", "deck"], name="vocabulary__user_id_eb9022_idx"
                    ),
                ],
                "unique_together": {("user", "deck")},
            },
        ),
        migrations.CreateModel(
            name="UserCardTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("difficult", "🔴 Difficult"),
                            ("review_later", "📝 Review Later"),
                            ("important", "⭐ Important"),
                            ("mastered", "✅ Mastered"),
                        ],
                        help_text="Type of tag applied to the card",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the tag was added"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about why this card was tagged",
                    ),
                ),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tags",
                        to="vocabulary.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Card Tag",
                "verbose_name_plural": "User Card Tags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "tag"], name="vocabulary__user_id_aa7de9_idx"
                    ),
                    models.Index(
                        fields=["flashcard", "tag"],
                        name="vocabulary__flashca_7d3e69_idx",
                    ),
                ],
                "unique_together": {("user", "flashcard", "tag")},
            },
        ),
    ]
