# Generated by Django 5.2.9 on 2025-12-08 07:21

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(db_index=True)),
                ('minutes_studied', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('flashcards_reviewed', models.PositiveIntegerField(default=0)),
                ('daily_goal_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Study Record',
                'verbose_name_plural': 'Daily Study Records',
                'db_table': 'daily_streaks',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily_xp', 'Daily XP'), ('daily_minutes', 'Daily Minutes'), ('weekly_lessons', 'Weekly Lessons'), ('monthly_flashcards', 'Monthly Flashcards'), ('course_completion', 'Course Completion')], db_index=True, max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('target_value', models.PositiveIntegerField(verbose_name='Mục tiêu')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Hiện tại')),
                ('is_active', models.BooleanField(default=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mục tiêu học tập',
                'verbose_name_plural': 'Mục tiêu học tập',
                'db_table': 'learning_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partially Correct'), ('skipped', 'Skipped')], db_index=True, max_length=10)),
                ('user_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Thời gian phản hồi (ms)')),
                ('quality_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Quality Rating (SRS)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kết quả luyện tập',
                'verbose_name_plural': 'Kết quả luyện tập',
                'db_table': 'practice_results',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('flashcard', 'Flashcard Review'), ('dictation', 'Dictation'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('writing', 'Writing'), ('test', 'Practice Test'), ('mixed', 'Mixed Practice')], db_index=True, max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('correct_items', models.PositiveIntegerField(default=0)),
                ('incorrect_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Thời gian (giây)')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết phiên')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phiên luyện tập',
                'verbose_name_plural': 'Phiên luyện tập',
                'db_table': 'practice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='active', max_length=10)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tiến độ (%)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đăng ký khóa học',
                'verbose_name_plural': 'Đăng ký khóa học',
                'db_table': 'user_course_enrollments',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_level', models.PositiveSmallIntegerField(default=0, verbose_name='SRS Box Level (0-6)')),
                ('ease_factor', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=4, verbose_name='Ease Factor')),
                ('next_review_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày ôn tập tiếp theo')),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('is_mastered', models.BooleanField(db_index=True, default=False, verbose_name='Đã thành thạo')),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Flashcard',
                'verbose_name_plural': 'User Flashcards',
                'db_table': 'user_flashcards',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=15)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('best_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Điểm cao nhất (%)')),
                ('last_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Điểm gần nhất (%)')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Tổng thời gian học (giây)')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tiến độ bài học',
                'verbose_name_plural': 'Tiến độ bài học',
                'db_table': 'user_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='UserSentenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictation_attempts', models.PositiveIntegerField(default=0)),
                ('dictation_correct', models.PositiveIntegerField(default=0)),
                ('listening_attempts', models.PositiveIntegerField(default=0)),
                ('listening_correct', models.PositiveIntegerField(default=0)),
                ('speaking_attempts', models.PositiveIntegerField(default=0)),
                ('best_dictation_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('best_speaking_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_mastered', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_practiced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Sentence Progress',
                'verbose_name_plural': 'User Sentence Progress',
                'db_table': 'user_sentence_progress',
            },
        ),
    ]
