# Generated by Django 5.2.9 on 2025-12-08 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystreak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_results', to='curriculum.flashcard'),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_results', to='curriculum.sentence'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='study.practicesession'),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='current_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='curriculum.unit'),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.flashcard'),
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.sentence'),
        ),
        migrations.AddField(
            model_name='usersentenceprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailystreak',
            index=models.Index(fields=['user', 'study_date'], name='daily_strea_user_id_e61c18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystreak',
            unique_together={('user', 'study_date')},
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['user', 'is_active'], name='learning_go_user_id_ff16c8_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['user', 'goal_type'], name='learning_go_user_id_28839b_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'session_type'], name='practice_se_user_id_5a9e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'started_at'], name='practice_se_user_id_93c122_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['session_type', 'started_at'], name='practice_se_session_a1b58f_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceresult',
            index=models.Index(fields=['session', 'result'], name='practice_re_session_d7e71f_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['user', 'status'], name='user_course_user_id_db5957_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['course', 'status'], name='user_course_course__03826a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='userflashcard',
            index=models.Index(fields=['user', 'next_review_date'], name='user_flashc_user_id_c5e478_idx'),
        ),
        migrations.AddIndex(
            model_name='userflashcard',
            index=models.Index(fields=['user', 'is_mastered'], name='user_flashc_user_id_1f855b_idx'),
        ),
        migrations.AddIndex(
            model_name='userflashcard',
            index=models.Index(fields=['user', 'box_level'], name='user_flashc_user_id_426a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userflashcard',
            unique_together={('user', 'flashcard')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'status'], name='user_lesson_user_id_64b223_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='user_lesson_lesson__b56751_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'last_accessed_at'], name='user_lesson_user_id_598328_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='usersentenceprogress',
            index=models.Index(fields=['user', 'is_mastered'], name='user_senten_user_id_828c73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersentenceprogress',
            unique_together={('user', 'sentence')},
        ),
    ]
