# Generated by Django 5.2.9 on 2025-12-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_phoneme_preferred_audio_source'),
        ('study', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscriminationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='UUID for this session', max_length=36, unique=True, verbose_name='ID phiên')),
                ('total_questions', models.PositiveSmallIntegerField(default=10, verbose_name='Tổng số câu')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0, verbose_name='Số câu đúng')),
                ('accuracy', models.FloatField(default=0.0, help_text='Percentage: 0-100', verbose_name='Độ chính xác (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành')),
                ('time_limit_seconds', models.PositiveIntegerField(default=300, verbose_name='Giới hạn thời gian (giây)')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Thời gian đã dùng (giây)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrimination_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên phân biệt âm',
                'verbose_name_plural': 'Phiên phân biệt âm',
                'db_table': 'discrimination_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscriminationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('which_word', 'Which word did you hear?'), ('same_different', 'Are these the same or different?')], default='which_word', max_length=20, verbose_name='Loại câu hỏi')),
                ('question_number', models.PositiveSmallIntegerField(help_text='Question number within session (1-10)', verbose_name='Số câu hỏi')),
                ('correct_word', models.CharField(choices=[('word_1', 'Word 1'), ('word_2', 'Word 2')], max_length=10, verbose_name='Từ đúng')),
                ('user_answer', models.CharField(choices=[('word_1', 'Word 1'), ('word_2', 'Word 2')], max_length=10, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(verbose_name='Đúng')),
                ('response_time', models.FloatField(help_text='Time taken to answer in seconds', verbose_name='Thời gian phản hồi (giây)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('minimal_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.minimalpair', verbose_name='Cặp tối thiểu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrimination_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study.discriminationsession', verbose_name='Phiên')),
            ],
            options={
                'verbose_name': 'Lần thử phân biệt âm',
                'verbose_name_plural': 'Lần thử phân biệt âm',
                'db_table': 'discrimination_attempts',
                'ordering': ['session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(help_text='Audio file (WebM, MP4, etc.)', upload_to='user_recordings/%Y/%m/%d/', verbose_name='File ghi âm')),
                ('duration_seconds', models.FloatField(help_text='Recording duration in seconds', verbose_name='Thời lượng (giây)')),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='Kích thước file (bytes)')),
                ('mime_type', models.CharField(default='audio/webm', max_length=50, verbose_name='Loại MIME')),
                ('self_assessment_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star - Need more practice'), (2, '2 Stars - Getting better'), (3, '3 Stars - Good attempt'), (4, '4 Stars - Very good'), (5, '5 Stars - Native-like')], help_text='User self-rating (1-5 stars)', null=True, verbose_name='Tự đánh giá (1-5 sao)')),
                ('ai_score', models.FloatField(blank=True, help_text='AI pronunciation analysis score (0-100). Future feature.', null=True, verbose_name='Điểm AI (0-100)')),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated pronunciation feedback. Future feature.', verbose_name='Phản hồi từ AI')),
                ('is_best', models.BooleanField(db_index=True, default=False, help_text="Mark as user's best recording for this phoneme", verbose_name='Ghi âm tốt nhất')),
                ('notes', models.TextField(blank=True, help_text='User notes about this recording', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recordings', to='curriculum.phoneme', verbose_name='Âm vị')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ghi âm phát âm',
                'verbose_name_plural': 'Ghi âm phát âm',
                'db_table': 'production_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discriminationsession',
            index=models.Index(fields=['user', '-started_at'], name='discriminat_user_id_fef81d_idx'),
        ),
        migrations.AddIndex(
            model_name='discriminationsession',
            index=models.Index(fields=['status', '-started_at'], name='discriminat_status_b7eba6_idx'),
        ),
        migrations.AddIndex(
            model_name='discriminationattempt',
            index=models.Index(fields=['user', '-created_at'], name='discriminat_user_id_af579e_idx'),
        ),
        migrations.AddIndex(
            model_name='discriminationattempt',
            index=models.Index(fields=['session', 'question_number'], name='discriminat_session_559ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecording',
            index=models.Index(fields=['user', 'phoneme', '-created_at'], name='production__user_id_eef22f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrecording',
            index=models.Index(fields=['user', 'is_best'], name='production__user_id_bf4e64_idx'),
        ),
    ]
